"""Generate V3 Kaggle GPU training jobs after all training shards pass QC."""
from __future__ import annotations

import argparse
import base64
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SFCN_URL = "https://raw.githubusercontent.com/ha-ha-ha-han/UKBiobank_deep_pretrain/master/brain_age/run_20190719_00_epoch_best_mae.p"
SFCN_SHA256 = "f9197c92486a8dba7fd87bb9f2ecc4f42f7c9628b9150d1b95c8a5ac10721ad3"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("model", choices=("sfcn", "resnet"))
    parser.add_argument("--suffix", default="")
    parser.add_argument("--head-epochs", type=int, default=20)
    parser.add_argument("--block-epochs", type=int, default=12)
    parser.add_argument("--patience", type=int, default=5)
    parser.add_argument("--warm-start-kernel")
    parser.add_argument("--warm-start-sha256")
    parser.add_argument("--sfcn-refine", action="store_true")
    parser.add_argument("--sfcn-deeper-refine", action="store_true")
    parser.add_argument("--age-balanced-sampling", action="store_true")
    parser.add_argument("--sfcn-contrast-augment", action="store_true")
    parser.add_argument("--sfcn-target-sigma", type=float, default=2.)
    parser.add_argument("--sfcn-precision-loss", action="store_true")
    parser.add_argument("--sfcn-rounded-interval-loss", action="store_true")
    parser.add_argument("--sfcn-rounded-interval-nll", action="store_true")
    parser.add_argument("--refine-lr-scale", type=float, default=1.)
    parser.add_argument("--qc-approval", type=Path,
                        default=ROOT / "artifacts/v3/qc/approval.json")
    args = parser.parse_args()
    if args.sfcn_rounded_interval_nll and (not args.sfcn_refine or args.sfcn_precision_loss
                                         or args.sfcn_rounded_interval_loss):
        parser.error("Interval NLL requires refinement and replaces other precision auxiliaries")
    if args.sfcn_rounded_interval_loss and (not args.sfcn_refine or args.sfcn_precision_loss):
        parser.error("Rounded interval loss requires refinement and replaces precision loss")
    if args.sfcn_precision_loss and not args.sfcn_refine:
        parser.error("Precision loss requires SFCN refinement")
    if (not math.isfinite(args.sfcn_target_sigma) or not .5 <= args.sfcn_target_sigma <= 2.
            or (args.sfcn_target_sigma != 2. and not args.sfcn_refine)):
        parser.error("Target sigma must be in [0.5, 2]; nondefault requires SFCN refinement")
    if args.sfcn_contrast_augment and not args.sfcn_refine:
        parser.error("Contrast augmentation requires SFCN refinement")
    if args.sfcn_deeper_refine and not args.sfcn_refine:
        parser.error("Deeper refinement requires SFCN refinement")
    if args.age_balanced_sampling and not args.sfcn_refine:
        parser.error("Age-balanced sampling requires SFCN refinement")
    if (not math.isfinite(args.refine_lr_scale) or not 0 < args.refine_lr_scale <= 1
            or (args.refine_lr_scale != 1. and not args.sfcn_refine)):
        parser.error("Learning-rate scale requires refinement and must be in (0, 1]")
    if args.sfcn_refine and (args.model != "sfcn" or not args.warm_start_kernel or args.head_epochs != 0):
        parser.error("SFCN refinement requires SFCN warm-start and zero head epochs")
    if args.suffix and not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", args.suffix):
        parser.error("Suffix must be a lowercase Kaggle slug")
    if bool(args.warm_start_kernel) != bool(args.warm_start_sha256):
        parser.error("Warm-start kernel and checksum must be supplied together")
    if args.warm_start_kernel and not args.suffix:
        parser.error("Warm-start runs require a new suffix to preserve their parent")
    suffix = f"-{args.suffix}" if args.suffix else ""
    sources = [f"asildoangm/brainage-v3-merge-{source}"
               for source in ("ixi", "sald", "nimh")]
    if args.warm_start_kernel:
        sources.append(args.warm_start_kernel)
    target = ROOT / "kaggle" / (f"v3_train_{args.model}" + suffix.replace("-", "_"))
    target.mkdir(parents=True, exist_ok=True)
    files = {name: base64.b64encode((ROOT / name).read_bytes()).decode("ascii") for name in
             ("brainage.py", "v3_model.py", "v3_train.py", "v3_inputs.py")}
    catalog = base64.b64encode((ROOT / "artifacts/v3/catalog/catalog.csv").read_bytes()).decode("ascii")
    approval = (base64.b64encode(args.qc_approval.read_bytes()).decode("ascii")
                if args.qc_approval.is_file() else "")
    launcher = f'''# Generated by tools/build_v3_train_kaggle.py.
import base64
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import requests
os.environ["OMP_NUM_THREADS"] = "2"
os.environ["OPENBLAS_NUM_THREADS"] = "2"
os.environ["MPLCONFIGDIR"] = "/tmp/brainage-matplotlib"
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "numpy==1.26.4", "pandas==2.2.3", "scipy==1.14.1",
                "scikit-learn==1.5.2", "nibabel==5.3.2", "nipype==1.10.0",
                "xlrd==2.0.1", "matplotlib==3.9.2", "requests>=2.32,<3"], check=True)
root = Path("/kaggle/working")
for name, encoded in {files!r}.items():
    (root / name).write_bytes(base64.b64decode(encoded))
(root / "catalog.csv").write_bytes(base64.b64decode({catalog!r}))
if not {bool(approval)!r}:
    raise RuntimeError("Human visual QC approval is required before V3 training")
(root / "qc_approval.json").write_bytes(base64.b64decode({approval!r}))
sys.path.insert(0, str(root))
from v3_inputs import discover_cohorts, verify_qc_approval, find_checkpoint_by_hash
cohorts = discover_cohorts(Path("/kaggle/input"), ("IXI", "SALD", "NIMH"),
                           root / "catalog.csv")
verify_qc_approval(cohorts, root / "qc_approval.json", root / "catalog.csv")
prepared = Path("/tmp/brainage-v3-prepared")
prepared.mkdir(parents=True, exist_ok=True)
for source, path in cohorts.items():
    (prepared / source.lower()).symlink_to(path)
model = {args.model!r}
command = [sys.executable, str(root / "v3_train.py"), "--catalog", str(root / "catalog.csv"),
           "--prepared-root", str(prepared), "--output", str(root / "training"),
           "--model", model, "--batch", "2", "--accumulation", "4",
           "--head-epochs", {str(args.head_epochs)!r}, "--block-epochs", {str(args.block_epochs)!r},
           "--patience", {str(args.patience)!r}, "--sfcn-target-sigma", {str(args.sfcn_target_sigma)!r}]
warm_kernel = {args.warm_start_kernel!r}
if {args.sfcn_refine!r}:
    command.extend(["--sfcn-refine", "--refine-lr-scale", {str(args.refine_lr_scale)!r}])
if {args.age_balanced_sampling!r}:
    command.append("--age-balanced-sampling")
if {args.sfcn_contrast_augment!r}:
    command.append("--sfcn-contrast-augment")
if {args.sfcn_deeper_refine!r}:
    command.append("--sfcn-deeper-refine")
if {args.sfcn_precision_loss!r}:
    command.append("--sfcn-precision-loss")
if {args.sfcn_rounded_interval_loss!r}:
    command.append("--sfcn-rounded-interval-loss")
if {args.sfcn_rounded_interval_nll!r}:
    command.append("--sfcn-rounded-interval-nll")
if warm_kernel:
    parent = find_checkpoint_by_hash(Path("/kaggle/input"), {args.warm_start_sha256!r})
    command.extend(["--warm-start", str(parent), "--warm-start-sha256",
                    {args.warm_start_sha256!r}])
if model == "sfcn":
    weights = root / "sfcn_pretrained.p"
    with requests.get({SFCN_URL!r}, stream=True, timeout=(30, 180)) as response:
        response.raise_for_status()
        with weights.open("wb") as stream:
            for chunk in response.iter_content(1024 * 1024):
                if chunk:
                    stream.write(chunk)
    digest = hashlib.sha256(weights.read_bytes()).hexdigest()
    if digest != {SFCN_SHA256!r}:
        raise ValueError("SFCN pretrained weights checksum mismatch")
    command.extend(["--sfcn-weights", str(weights), "--sfcn-sha256", digest])
subprocess.run(command, check=True)
'''
    (target / "run.py").write_text(launcher)
    metadata = {"id": f"asildoangm/brainage-v3-train-{args.model}{suffix}",
                "title": f"BrainAGE V3 Train {args.model.upper()}" + (f" {args.suffix}" if args.suffix else ""), "code_file": "run.py",
                "language": "python", "kernel_type": "script", "is_private": True,
                "enable_gpu": True, "enable_internet": True,
                "dataset_sources": [], "competition_sources": [], "model_sources": [],
                "kernel_sources": sources}
    (target / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2))
    print(target)
    if not approval:
        print("QC approval absent: generated training job will refuse to run")


if __name__ == "__main__":
    main()
