"""Build one portable, QC-reviewable Kaggle output per prepared V3 cohort."""
from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHARDS = {"IXI": 8, "SALD": 8, "NIMH": 4, "DLBS": 8}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", choices=SHARDS)
    args = parser.parse_args()
    source = args.source
    count = SHARDS[source]
    target = ROOT / "kaggle" / f"v3_merge_{source.lower()}"
    target.mkdir(parents=True, exist_ok=True)
    files = {name: base64.b64encode((ROOT / name).read_bytes()).decode("ascii")
             for name in ("brainage.py", "v3_merge.py", "tools/v3_qc_sheets.py")}
    catalog = base64.b64encode((ROOT / "artifacts/v3/catalog/catalog.csv").read_bytes()).decode("ascii")
    launcher = f'''# Generated by tools/build_v3_merge_kaggle.py.
import base64
import json
import os
from pathlib import Path
import subprocess
import sys
os.environ["OMP_NUM_THREADS"] = "2"
os.environ["OPENBLAS_NUM_THREADS"] = "2"
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "numpy==1.26.4", "pandas==2.2.3", "pillow>=10,<12"], check=True)
root = Path("/kaggle/working")
for name, encoded in {files!r}.items():
    path = root / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(base64.b64decode(encoded))
(root / "catalog.csv").write_bytes(base64.b64decode({catalog!r}))
sys.path.insert(0, str(root))
from v3_merge import merge
from tools.v3_qc_sheets import select_review, save_sheets
source = {source!r}
shards = []
for path in Path("/kaggle/input").rglob("prepare_summary.json"):
    summary = json.loads(path.read_text())
    if summary.get("source") == source:
        shards.append(path.parent)
if len(shards) != {count}:
    raise RuntimeError(f"Expected {count} {{source}} shards, got {{shards}}")
merge(root / "catalog.csv", shards, root / "prepared", sources=(source,),
      materialize=True)
review, failed = select_review([root / "prepared" / source.lower()], per_site=12)
qc = root / "qc_review"
qc.mkdir(exist_ok=True)
review.to_csv(qc / "qc_review_index.csv", index=False)
failed.to_csv(qc / "qc_automatic_failures.csv", index=False)
save_sheets(review, qc)
print("V3_SOURCE_MERGE_COMPLETE", source, len(review), len(failed), flush=True)
'''
    (target / "run.py").write_text(launcher)
    metadata = {"id": f"asildoangm/brainage-v3-merge-{source.lower()}",
                "title": f"BrainAGE V3 Merge {source}", "code_file": "run.py",
                "language": "python", "kernel_type": "script", "is_private": True,
                "enable_gpu": False, "enable_internet": True,
                "dataset_sources": [], "competition_sources": [], "model_sources": [],
                "kernel_sources": [f"asildoangm/brainage-v3-prepare-{source.lower()}-{i}-of-{count}"
                                   for i in range(count)]}
    (target / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2))
    print(target)


if __name__ == "__main__":
    main()
