"""Generate self-contained, auditable Kaggle preparation scripts for V3."""
from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ("SALD", "NIMH", "DLBS", "IXI")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", choices=SOURCES)
    parser.add_argument("--shard-index", type=int, default=0)
    parser.add_argument("--shard-count", type=int, default=1)
    parser.add_argument("--workers", type=int, default=2)
    args = parser.parse_args()
    source = args.source
    if args.shard_count < 1 or not 0 <= args.shard_index < args.shard_count:
        parser.error("invalid shard")
    if not 1 <= args.workers <= 4:
        parser.error("workers must be 1..4")
    suffix = f"-{args.shard_index}-of-{args.shard_count}" if args.shard_count > 1 else ""
    target = ROOT / "kaggle" / f"v3_prepare_{source.lower()}{suffix.replace('-', '_')}"
    target.mkdir(parents=True, exist_ok=True)
    files = {name: base64.b64encode((ROOT / name).read_bytes()).decode("ascii")
             for name in ("brainage.py", "v3_prepare.py", "v3_data.py")}
    catalog = base64.b64encode((ROOT / "artifacts/v3/catalog/catalog.csv").read_bytes()).decode("ascii")
    launcher = f'''# Generated by tools/build_v3_kaggle.py from the locked local source.
import base64
import os
from pathlib import Path
import subprocess
import sys
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MPLCONFIGDIR"] = "/tmp/brainage-matplotlib"
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "numpy==1.26.4", "pandas==2.2.3", "scipy==1.14.1",
                "scikit-learn==1.5.2", "nibabel==5.3.2", "nipype==1.10.0",
                "xlrd==2.0.1", "matplotlib==3.9.2", "requests>=2.32,<3",
                "openpyxl==3.1.5", "nipreps-synthstrip==0.0.1"], check=True)
root = Path("/kaggle/working")
for name, encoded in {files!r}.items():
    (root / name).write_bytes(base64.b64decode(encoded))
(root / "catalog.csv").write_bytes(base64.b64decode({catalog!r}))
sys.path.insert(0, str(root))
from v3_prepare import prepare
source = {source!r}
ixi_prepared = Path("/kaggle/input")
if source == "IXI":
    matches = sorted(Path("/kaggle/input").rglob("prepare_summary.json"))
    if len(matches) != 1:
        raise RuntimeError(f"Expected one V2 IXI prepared source, got {{matches}}")
    ixi_prepared = matches[0].parent
result = prepare(root / "catalog.csv", source, root / "prepared", Path("/tmp/brainage"),
                 Path("/kaggle/input"), ixi_prepared, workers={args.workers},
                 shard_index={args.shard_index}, shard_count={args.shard_count})
print("V3_PREPARE_COMPLETE", result, flush=True)
'''
    (target / "run.py").write_text(launcher)
    metadata = {"id": f"asildoangm/brainage-v3-prepare-{source.lower()}{suffix}",
                "title": f"BrainAGE V3 Prepare {source}{suffix}", "code_file": "run.py",
                "language": "python", "kernel_type": "script", "is_private": True,
                "enable_gpu": False, "enable_internet": True,
                "dataset_sources": ["kbacon/ixi-t1"] if source == "IXI" else [],
                "competition_sources": [], "model_sources": [],
                "kernel_sources": ["asildoangm/brainage-ixi-prepare"] if source == "IXI" else []}
    (target / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2))
    print(target)


if __name__ == "__main__":
    main()
