"""Bundle the audited local source into a self-contained Kaggle script."""
import argparse
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('stage', choices=['prepare', 'train'])
    parser.add_argument('--member', type=int, choices=range(5), default=0)
    args = parser.parse_args()
    target = ROOT / 'kaggle' / (args.stage if args.stage == 'prepare' else f'train_member_{args.member}')
    target.mkdir(parents=True, exist_ok=True)
    source = base64.b64encode((ROOT / 'brainage.py').read_bytes()).decode()
    dependencies = [line for line in (ROOT / 'requirements.txt').read_text().splitlines() if not line.startswith('torch')]
    command = (['prepare', '--images', '/kaggle/input', '--output', '/kaggle/working/prepared',
                '--cache', '/tmp/brainage', '--workers', '4'] if args.stage == 'prepare' else
               ['train', '--prepared', 'DISCOVER', '--output', '/kaggle/working/training',
                '--cache', '/tmp/brainage', '--member', str(args.member)])
    launcher = f'''# Generated by tools/build_kaggle.py; edit brainage.py, not this file.
import base64
import os
from pathlib import Path
import subprocess
import sys
os.environ['OMP_NUM_THREADS'] = '2'
os.environ['OPENBLAS_NUM_THREADS'] = '2'
os.environ['MPLCONFIGDIR'] = '/tmp/brainage-matplotlib'
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q'] + {dependencies!r}, check=True)
source = Path('/kaggle/working/brainage.py')
source.write_bytes(base64.b64decode({source!r}))
command = {command!r}
if 'DISCOVER' in command:
    matches = sorted(Path('/kaggle/input').rglob('prepare_summary.json'))
    if len(matches) != 1:
        raise RuntimeError(f'Expected one prepared dataset, found {{matches}}')
    command[command.index('DISCOVER')] = str(matches[0].parent)
subprocess.run([sys.executable, str(source)] + command, check=True)
'''
    (target / 'run.py').write_text(launcher)
    slug = args.stage if args.stage == 'prepare' else f'train-member-{args.member}'
    title = args.stage.title() if args.stage == 'prepare' else f'Train Member {args.member}'
    metadata = {'id': f'asildoangm/brainage-ixi-{slug}',
        'title': f'BrainAGE IXI {title}', 'code_file': 'run.py',
        'language': 'python', 'kernel_type': 'script', 'is_private': True,
        'enable_gpu': args.stage == 'train', 'enable_internet': True,
        'dataset_sources': ['kbacon/ixi-t1'] if args.stage == 'prepare' else [],
        'competition_sources': [], 'model_sources': [],
        'kernel_sources': ['asildoangm/brainage-ixi-prepare'] if args.stage == 'train' else []}
    (target / 'kernel-metadata.json').write_text(json.dumps(metadata, indent=2))
    print(target)


if __name__ == '__main__':
    main()
